### ISSUE TITLE
Cannot be executed from /tmp 

### ISSUE THREAD

**Issue by philwinkle** [lbdremy/solr-install#3]
In Redhat Enterprise Linux you cannot execute from /tmp because /tmp is mounted as noexec. On attempt it gives you the following errror: "bad interpreter: Permission denied"

The install process should prompt for this in these distros or you should ammend your installation procedure in README.md to annotate this.

**Comment by lbdremy** [comment]
@philwinkle thanks. I will add a note in the README.
